[window]
opacity = 0.5

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
   { key = "Return", mods = "Control", action = "SpawnNewInstance" },
   { key = "PageUp", action = "ScrollLineUp" },
   { key = "PageDown", action = "ScrollLineDown" }
]

[font]
normal = {family = "JetBrainsMono Nerd Font", style = "Regular"}
